version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - USER=postgres
      - DB=${DB}
      - PASSWORD=${PASSWORD}
      - SYNC=${_SYNC}
      - AUTO=${AUTO}
    volumes:
       - ./new-postgres-data:/var/lib/postgresql/new-data